backend:
    name: git-gateway

branch: master # Branch to update (optional; defaults to master)
logo_url: https://www.dealicia.com/images/logo.png

# These lines should *not* be indented
media_folder: "static/images/" # Media files will be stored in the repo under static/images
public_folder: "images/" # The src attribute for uploaded media will begin with /images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/spanish/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Temas", name: "temas", widget: "select", multiple: true, options: ["Almuerzo", "Desayunos", "Monta tu mesa", "Quiches", "Reutilizar / reciclar", "Tartas", "Viaja a través de la gastronomía"]}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "mantequillas" # Used in routes, e.g., /admin/collections/blog
    label: "Mantequillas" # Used in the UI
    folder: "content/spanish/product/mantequillas" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "product"}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Categories", name: "category", widget: "select", multiple: true, options: ["Mantequillas"]}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Product Weight (g)", name: "weight", widget: "number"}
      - {label: "Product Shipping Weight (g)", name: "productWeight", widget: "number"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "In Stock", name: "stock", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "mermeladas" # Used in routes, e.g., /admin/collections/blog
    label: "Mermeladas" # Used in the UI
    folder: "content/spanish/product/mermeladas" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "product"}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Categories", name: "category", widget: "select", multiple: true, options: ["Mermeladas"]}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Product Weight (g)", name: "weight", widget: "number"}
      - {label: "Product Shipping Weight (g)", name: "productWeight", widget: "number"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "In Stock", name: "stock", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "galletas" # Used in routes, e.g., /admin/collections/blog
    label: "Galletas" # Used in the UI
    folder: "content/spanish/product/galletas" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "product"}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Categories", name: "category", widget: "select", multiple: true, options: ["Galletas Dulces", "Galletas Saladas"]}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Product Weight (g)", name: "weight", widget: "number"}
      - {label: "Product Shipping Weight (g)", name: "productWeight", widget: "number"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "In Stock", name: "stock", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "saludables" # Used in routes, e.g., /admin/collections/blog
    label: "Saludables" # Used in the UI
    folder: "content/spanish/product/saludables" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Type", name: "type", widget: "hidden", default: "product"}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Categories", name: "category", widget: "select", multiple: true, options: ["Saludables"]}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Product Weight (g)", name: "weight", widget: "number"}
      - {label: "Product Shipping Weight (g)", name: "productWeight", widget: "number"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "In Stock", name: "stock", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "chocolates" # Used in routes, e.g., /admin/collections/blog
    label: "Chocolates" # Used in the UI
    folder: "content/spanish/product/chocolates" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "product"}
      - {label: "Main Image - 1024x768px", name: "image", widget: "image", default: "/images/template_l.png"}
      - {label: "Thumbnail - 586x648px", name: "thumb", widget: "image", default: "/images/template_thumb.png"}
      - {label: "Categories", name: "category", widget: "select", multiple: true, options: ["Mermeladas"]}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Product Weight (g)", name: "weight", widget: "number"}
      - {label: "Product Shipping Weight (g)", name: "productWeight", widget: "number"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "In Stock", name: "stock", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "tartas" # Used in routes, e.g., /admin/collections/blog
    label: "Tartas" # Used in the UI
    folder: "content/spanish/product/tartas" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}


  #EXTRA PAGES#####################################################################
  - label: "Legal"
    name: "pages"
    files:
        ## START
      - label: "Condiciones de compra"
        name: "condiciones_compra"
        file: "content/spanish/legal/condiciones_compra.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        ## /END
      - label: "Aviso Legal"
        name: "avisolegal"
        file: "content/spanish/legal/avisolegal.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        ## /END
      - label: "Politica de Cookies"
        name: "politica_cookies"
        file: "content/spanish/legal/politica_cookies.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        ## /END
      - label: "Politica de privacidad"
        name: "politica_privacidad"
        file: "content/spanish/legal/politica_privacidad.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
        ## /END

  # Homepage Items ##############################################
  - label: "Homepage"
    name: "homez"
    files:
      - label: "Banner"
        name: "deal"
        file: "content/spanish/deal.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: string}
          - {label: Image, name: bg_image, widget: image}

  - label: "Settings"
    name: "settings"
    delete: false # users shouldnt be able to delete here.
    editor:
      preview: false
    files:
      - label: "Oferta"
        name: "deal"
        file: "data/es/homepage.yml"
        fields:
          - {label: 'Title', name: 'title', widget: string}
          - {label: 'Subtitle', name: 'subtitle', widget: string}
          - {label: 'Content', name: 'content', widget: string}
          - {label: 'Year', name: 'year', widget: string}
          - {label: 'Month', name: 'month', widget: string}
          - {label: 'Day', name: 'day', widget: string}
          - {label: 'Hour', name: 'hour', widget: string}
          - {label: 'Enabled', name: 'enable', widget: boolean}
